# -*- coding: utf-8 -*-
"""Практика 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlD63pL7-s_3AkPx7OwGyg6vhhI58WJB
"""

def restore_tree(code: str):
    nodes = [1]
    edges = []
    current = 1
    next_id = 1
    parent = {1: None}

    for symbol in code:
        if symbol == '0':
            next_id += 1
            nodes.append(next_id)
            edges.append((current, next_id))
            parent[next_id] = current
            current = next_id
        elif symbol == '1':
            if parent[current] is not None:
                current = parent[current]
        else:
            raise ValueError(f"Недопустимый символ {symbol}")

    return nodes, edges


def export_to_dot(nodes, edges, filename="tree.dot"):
    lines = ["graph Tree {"]
    lines.append('    node [shape=circle, style=filled, fontname="Arial"];')
    for n in nodes:
        color = "lightblue"
        lines.append(f'    {n} [fillcolor={color}];')
    for u, v in edges:
        lines.append(f'    {u} -- {v};')
    lines.append("}")
    dot = "\n".join(lines)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(dot)
    return dot


code = "00010011101100101011"

nodes, edges = restore_tree(code)
print(f"Вершины: {nodes}")
print(f"Рёбра:   {edges}")

dot = export_to_dot(nodes, edges, "tree.dot")
print("\n=== DOT ===")
print(dot, "\n")